### ISSUE TITLE
Make communication thread safe

### ISSUE THREAD

**Issue by jherkenhoff** [lobis/hvps#38]
While using this library in the context of an [EPICS](https://epics-controls.org/) server (using the [p4p](https://mdavidsaver.github.io/p4p/) python library), which is inherently multi-threaded, I encountered issues while multiple threads tried to communicated with the device.

For example, wrapping the `serial.write` and `serial.readline` functions together in a `threading.Lock` would avoid any possible race conditions by making sure that no other thread can take over the serial bus during a "transaction".

What do you think about this?
The problem would be: Where to store the `threading.Lock`?

**Comment by lobis** [comment]
Thanks for raising this, I am not 100% sure if this should be under the scope of this library but it's straightforward to implement, so we will add it for the time being.

I created a PR (https://github.com/lobis/hvps/pull/39) to continue the conversation.

**Comment by jherkenhoff** [comment]
Sorry for my very late reply. I only had the chance to look into this now.
It works perfect! No thread collisions at all, leading to much more stable operation of my device-server.
Thanks a lot @lobis !
